version: "3"

x-nvidia: &nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  compvis:
    build:
      context: "$PWD/compvis"
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - "$PWD/compvis/home:/home/app"
    environment:
      GH_REPO: CompVis/stable-diffusion
      COMMIT_HASH: 21f890f9da3cfbeaba8e2ac3c425ee9e998d5229
      MODEL_URL: https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt
      MODEL_SHA256: fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556
    # <<: *nvidia
